services:
  docs:
    build: ./mkdocs
    volumes:
      - ./mkdocs:/docs
      - ./notebooks:/docs/My_Notes/notebooks:ro 
    ports:
      - "127.0.0.1:11411:8000"
    command: serve -a 0.0.0.0:8000
  jupyter:
    image: jupyter/datascience-notebook:latest
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "127.0.0.1:11412:8888"   # 本机11412 → 容器8888（Jupyter）
    command: start-notebook.sh --ServerApp.token='' --ServerApp.password=''