name: debug-mkdocs
on:
  workflow_dispatch:   # 手動觸發

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true   # 如果 notebooks 用 Git LFS 的話一定要開

      - name: List repo structure
        run: |
          echo "=== TOP LEVEL ==="
          ls -lah
          echo "=== mkdocs/ tree ==="
          find mkdocs -maxdepth 3 -type f | sort

      - name: Show mkdocs.yml docs_dir and notebooks
        run: |
          pip install pyyaml
          python - <<'PY'
          import yaml, pathlib
          cfg = yaml.safe_load(open("mkdocs/mkdocs.yml"))
          docs_dir = pathlib.Path("mkdocs") / cfg.get("docs_dir","docs")
          print("docs_dir =", docs_dir.resolve())
          for nb in docs_dir.rglob("*.ipynb"):
              print("FOUND NOTEBOOK:", nb)
          PY

      - name: Build mkdocs site
        run: |
          docker build -t mkdocs-site ./mkdocs
          docker run --rm -v "$PWD/mkdocs":/docs mkdocs-site build --clean

      - name: List built site
        run: |
          echo "=== SITE OUTPUT ==="
          find mkdocs/site -maxdepth 3 -type f | sort | head -n 100